# Generated by Django 3.2.19 on 2023-05-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minuites',
            new_name='time_minutes',
        ),
    ]
